{% set version = "1.0.12" %}

package:
  name: perl-debug-adapter
  version: {{ version }}

source:
  url: https://github.com/Nihilus118/perl-debug-adapter/archive/{{ version }}.tar.gz
  sha256: ce25f70dbd19f0ff09ad0e339734c9f43cefd1be633d09a440430d68ac68c3ab

build:
  noarch: generic
  number: 0

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - perl-debug-adapter &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/Nihilus118/perl-debug-adapter
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Debug adapter for Perl
  dev_url: https://github.com/Nihilus118/perl-debug-adapter

extra:
  recipe-maintainers:
    - danielnachun
