{% set version = "1.0.9" %}

package:
  name: perl-debug-adapter
  version: {{ version }}

source:
  url: https://github.com/Nihilus118/perl-debug-adapter/archive/{{ version }}.tar.gz
  sha256: 3caf79271bbad6cd7adf294dd52d460f04322b1abce6142d353694e2dff53c5b

build:
  noarch: generic
  number: 0

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - perl-debug-adapter &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/Nihilus118/perl-debug-adapter
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Debug adapter for Perl
  dev_url: https://github.com/Nihilus118/perl-debug-adapter

extra:
  recipe-maintainers:
    - danielnachun
